"""empty message

Revision ID: 6fe99881578d
Revises: 92b26407c566
Create Date: 2023-05-27 22:03:27.560004

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6fe99881578d'
down_revision = '92b26407c566'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('listings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('team_description', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('role_description', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('responsibilities', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('benefits_compensation', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('listings', schema=None) as batch_op:
        batch_op.drop_column('benefits_compensation')
        batch_op.drop_column('responsibilities')
        batch_op.drop_column('role_description')
        batch_op.drop_column('team_description')

    # ### end Alembic commands ###
